-- ============================================================
-- Organizations
-- ============================================================
create or replace table organizations (
  id uuid primary key default gen_random_uuid() references auth.users(id) on delete cascade,
  name text,
  business_email text,
  first_name text,
  last_name text,
  agent_inbox_id text unique,
  is_agent_active boolean default false,
  created_at timestamptz default now()
);

-- ============================================================
-- Wallets  (session key + USDT balance only — no fiat/hedge assets)
-- ============================================================
create or replace table wallets (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references organizations(id) on delete cascade,

  public_session_key_address text,
  non_custodial_wallet_address text,

  usdt_balance numeric default 0,

  -- Encrypted session key private key (EOA)
  encrypted_session_key text,

  -- Serialized permission string from user's frontend approval
  -- Generated by frontend via serializePermissionAccount
  -- Stored here so the agent can deserialize it later
  session_key_approval text,

  -- Zerodev policy config: JSONB storing supplier whitelist, spend caps, rate limits
  -- Mirrors the on-chain CallPolicy/GasPolicy/RateLimitPolicy for fast local verification
  policy_config jsonb default '{}'::jsonb,

  -- Address of the Kernel smart account (set when frontend saves first approval)
  -- Used to read on-chain USDT balance of the org's smart account
  smart_account_address text,

  created_at timestamptz default now()
);

-- ============================================================
-- Suppliers
-- ============================================================
create or replace table suppliers (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references organizations(id) on delete cascade,

  name text,
  email text,
  non_custodial_wallet_address text,

  -- Whether this supplier's wallet has been verified against Zerodev on-chain session policy
  is_verified_onchain boolean default false,
  last_verified_onchain_at timestamptz,

  created_at timestamptz default now()
);

-- ============================================================
-- Inventory items
-- ============================================================
create or replace table inventory_items (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references organizations(id) on delete cascade,

  name text not null,
  unit_name text,

  unit_sales_price_in_usdt numeric,
  expected_purchase_price_in_usdt numeric,

  quantity integer default 0,
  in_transit_quantity integer default 0,
  inventory_capacity integer default 20,

  supplier_id uuid references suppliers(id),
  critical_order_level integer default 5,

  minimum_bulk_quantity integer default 10,

  -- Days from invoice request to delivery (used by procurement agent to decide when to reorder)
  supplier_lead_time_days integer default 2,

  last_restocked_at timestamptz,
  last_consumption_check_at timestamptz,
  is_agent_active boolean default true,

  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ============================================================
-- Inventory events  (sale, restock, invoice_requested, invoice_received, invoice_paid, fulfilled)
-- ============================================================
create or replace table inventory_events (
  id uuid primary key default gen_random_uuid(),

  organization_id uuid references organizations(id) on delete cascade,
  inventory_item_id uuid references inventory_items(id) on delete cascade,

  event_type text not null,
  -- sale | restock | invoice_requested | invoice_received | invoice_paid | manual_adjustment | fulfilled

  quantity_change integer,
  price_per_unit numeric,

  reference_id uuid,
  reference_type text,
  -- invoice | manual

  metadata jsonb,
  -- use metadata.fulfillment_status: 'pending' | 'fulfilled' for invoice_paid events

  created_at timestamptz default now()
);

-- ============================================================
-- Invoices  (received from suppliers)
-- ============================================================
create or replace table invoices (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references organizations(id) on delete cascade,

  supplier_id uuid references suppliers(id),
  inventory_item_id uuid references inventory_items(id),

  invoice_number text,
  total_amount numeric,
  currency text default 'USDT',

  due_date date,
  invoice_url text,

  status text default 'pending',
  -- pending | paid | scheduled

  received_at timestamptz default now()
);

-- ============================================================
-- Email inbox  (AgentMail received messages)
-- ============================================================
create or replace table email_inbox (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references organizations(id) on delete cascade,

  agent_inbox_id text references organizations(agent_inbox_id),

  sender text,
  subject text,
  body text,

  attachments text[],

  processed boolean default false,

  created_at timestamptz default now()
);

-- ============================================================
-- Crypto transactions  (USDT supplier payments)
-- ============================================================
create or replace table crypto_transactions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references organizations(id) on delete cascade,

  wallet_id uuid references wallets(id),

  type text,           -- supplier_payment
  status text default 'pending',

  amount numeric,
  currency text default 'USDT',

  destination_address text,
  blockchain_tx_hash text,

  created_at timestamptz default now()
);

-- ============================================================
-- Agent tasks  (procurement + payment task queue)
-- ============================================================
create or replace table agent_tasks (
  id uuid primary key default gen_random_uuid(),

  organization_id uuid references organizations(id) on delete cascade,

  agent_name text,

  task_type text not null,
  -- procurement.inventory_check | payment.process_invoice

  status text default 'pending',
  -- pending | processing | completed | failed

  priority integer default 1,

  payload jsonb,
  result jsonb,

  is_routine_task boolean default false,

  scheduled_for timestamptz,

  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  completed_at timestamptz
);

-- ============================================================
-- Notifications
-- ============================================================
create or replace table notifications (
  id uuid primary key default gen_random_uuid(),

  organization_id uuid references organizations(id) on delete cascade,

  title text,
  message text,
  type text,

  read boolean default false,
  metadata jsonb,

  created_at timestamptz default now()
);

-- ============================================================
-- Agent logs  (audit trail)
-- ============================================================
create or replace table agent_logs (
  id uuid primary key default gen_random_uuid(),

  organization_id uuid references organizations(id) on delete cascade,
  task_id uuid references agent_tasks(id) on delete set null,

  agent_name text,
  action_taken text,
  status text,
  thought text,
  metadata jsonb,

  started_task_at timestamptz not null,
  created_at timestamptz default now()
);

-- ============================================================
-- Indexes
-- ============================================================
create index idx_agent_tasks_status_scheduled on agent_tasks (status, scheduled_for asc);
create index idx_inventory_events_item_type on inventory_events (inventory_item_id, event_type, created_at desc);
create index idx_invoices_org_status on invoices (organization_id, status);

-- ============================================================
-- claim_next_task
-- Atomically claims the next eligible pending task (respecting scheduled_for),
-- picking one task per organization ordered by priority then age.
-- ============================================================
create or replace function claim_next_task()
returns setof agent_tasks
language plpgsql
as $$
begin
  return query
  with candidates as (
    select id, organization_id, priority, created_at
    from agent_tasks
    where status = 'pending'
      and (scheduled_for is null or scheduled_for <= now())
    order by organization_id, priority asc, created_at asc
    for update skip locked
  ),
  chosen as (
    select distinct on (organization_id) id
    from candidates
    order by organization_id, priority asc, created_at asc
  )
  update agent_tasks a
  set
    status     = 'processing',
    updated_at = now()
  from chosen c
  where a.id = c.id
  returning a.*;
end;
$$;


-- ============================================================
-- handle_new_org
-- Auto-creates an organizations row when a new Supabase auth user signs up.
-- ============================================================
create or replace function public.handle_new_org()
returns trigger as $$
begin
  insert into public.organizations (id)
  values (new.id);
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_org();

-- ============================================================
-- set_updated_at
-- Generic trigger function to keep updated_at current.
-- ============================================================
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create or replace trigger trg_inventory_items_updated_at
  before update on inventory_items
  for each row execute procedure set_updated_at();

create or replace trigger trg_agent_tasks_updated_at
  before update on agent_tasks
  for each row execute procedure set_updated_at();

-- ============================================================
-- confirm_inventory_fulfillment
-- When the user confirms goods have arrived, this function:
--   1. Marks the invoice_paid event as fulfilled
--   2. Decreases in_transit_quantity on the item
--   3. Increases quantity on the item
--   4. Inserts a restock event into inventory_events
-- ============================================================
create or replace function confirm_inventory_fulfillment(
  p_event_id uuid,
  p_item_id uuid,
  p_quantity integer
)
returns void
language plpgsql
as $$
begin
  -- Mark the invoice_paid event as fulfilled
  update inventory_events
  set metadata = jsonb_set(
    coalesce(metadata, '{}'::jsonb),
    '{fulfillment_status}',
    '"fulfilled"'::jsonb
  )
  where id = p_event_id;

  -- Move from in_transit to available stock
  update inventory_items
  set
    quantity = quantity + p_quantity,
    in_transit_quantity = greatest(0, in_transit_quantity - p_quantity)
  where id = p_item_id;

  -- Record a restock event so it shows in the inventory timeline
  insert into inventory_events (
    organization_id,
    inventory_item_id,
    event_type,
    quantity_change
  ) select
    organization_id,
    p_item_id,
    'restock',
    p_quantity
  from inventory_events
  where id = p_event_id
  limit 1;
end;
$$;

-- ============================================================
-- record_supplier_payment
-- After a payment confirms on-chain, this function:
--   1. Inserts an invoice_paid event into inventory_events
--   2. Increments in_transit_quantity on the inventory item
--   3. Marks the invoice as paid
-- ============================================================
create or replace function record_supplier_payment(
  p_organization_id uuid,
  p_inventory_item_id uuid,
  p_quantity integer,
  p_amount numeric,
  p_tx_hash text,
  p_supplier_id bigint default null,
  p_invoice_id bigint default null
)
returns void
language plpgsql
as $$
begin
  -- 1. Create the invoice_paid event
  insert into inventory_events (
    organization_id,
    inventory_item_id,
    event_type,
    quantity_change,
    price_per_unit,
    reference_type,
    metadata
  ) values (
    p_organization_id,
    p_inventory_item_id,
    'invoice_paid',
    p_quantity,
    p_amount / p_quantity,
    'invoice',
    jsonb_build_object('fulfillment_status', 'pending', 'transaction_hash', p_tx_hash)
  );

  -- 2. Increment in_transit on the item
  update inventory_items
  set in_transit_quantity = coalesce(in_transit_quantity, 0) + p_quantity
  where id = p_inventory_item_id;

  -- 3. Mark the invoice as paid (if it exists)
  if p_invoice_id is not null then
    update invoices
    set status = 'paid'
    where id = p_invoice_id and status = 'pending';
  end if;
end;
$$;

-- ============================================================
-- Migration helper: add columns if they don't already exist
-- Run this when upgrading an existing database
-- ============================================================
ALTER TABLE wallets ADD COLUMN IF NOT EXISTS policy_config jsonb DEFAULT '{}'::jsonb;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS is_verified_onchain boolean DEFAULT false;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS last_verified_onchain_at timestamptz;
